FROM python

ENV PYTHONBUFFERED 1
ENV DJANGO_SETTINGS_MODULE prod_settings

WORKDIR /app
COPY backend/. /app/.
# COPY prod_settings.py /app/prod_settings.py

RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

EXPOSE 8000
CMD python manage.py collectstatic --noinput \
    && python manage.py migrate \
    && uvicorn --host 0.0.0.0 app.asgi:application