# Generated by Django 5.2.6 on 2025-12-19 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0002_item_profilerole_shelf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelf",
            name="filial",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filial",
                to="esl.organizationfilial",
            ),
            preserve_default=False,
        ),
    ]
