# Generated by Django 5.2.6 on 2025-12-21 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0003_shelf_filial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shelf",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="Rack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("location", models.JSONField()),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filial",
                        to="esl.organizationfilial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ESL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("esl_id", models.TextField()),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esl_rack",
                        to="esl.rack",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="rack",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rack",
                to="esl.rack",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Shelf",
        ),
    ]
