# Generated by Django 5.2.6 on 2025-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0004_alter_product_shelf_rack_esl_product_rack_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="have_promotion",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(default=1, upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="prev_price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="short_name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
