# Generated by Django 5.2.6 on 2025-12-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0005_delete_item_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
