# Generated by Django 5.2.6 on 2025-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0006_integration_name_organization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationfilial",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organizationfilial",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="rack",
            name="location",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
