# Generated by Django 5.2.6 on 2025-12-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0007_alter_organizationfilial_end_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="esl",
            old_name="esl_id",
            new_name="esl_ip",
        ),
        migrations.AddField(
            model_name="esl",
            name="token",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
