# Generated by Django 5.2.6 on 2025-12-23 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0008_rename_esl_id_esl_esl_ip_esl_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rack",
                to="esl.rack",
            ),
        ),
    ]
