# Generated by Django 5.2.6 on 2025-12-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0009_alter_product_rack"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rack",
            name="location",
        ),
        migrations.AddField(
            model_name="organizationfilial",
            name="columns",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="organizationfilial",
            name="rows",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="rack",
            name="column",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rack",
            name="row",
            field=models.IntegerField(default=0),
        ),
    ]
