# Generated by Django 5.2.6 on 2026-02-23 03:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0010_remove_rack_location_organizationfilial_columns_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("external_id", models.TextField(blank=True, null=True)),
                ("integration_login", models.TextField(blank=True, null=True)),
                ("integration_password", models.TextField(blank=True, null=True)),
                ("integration_url", models.TextField(blank=True, null=True)),
                ("polling_frequency", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompanyFilial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("external_id", models.TextField(blank=True, null=True)),
                ("rows", models.IntegerField(default=3)),
                ("columns", models.IntegerField(default=3)),
                ("local_bridge_url", models.TextField(blank=True, null=True)),
                ("local_bridge_token", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filial_company",
                        to="esl.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ESLError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2026, 2, 23, 11, 13, 32, 35373),
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Firmware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "date_add",
                    models.DateField(
                        blank=True, default=datetime.date(2026, 2, 23), null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="integration",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="general_manager",
        ),
        migrations.RemoveField(
            model_name="organizationfilial",
            name="organization",
        ),
        migrations.DeleteModel(
            name="ProfileRole",
        ),
        migrations.RemoveField(
            model_name="product",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="have_promotion",
        ),
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="product",
            name="prev_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="external_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rack",
            name="shelfs_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="esl",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="esl_rack",
                to="esl.rack",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="rack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_rack",
                to="esl.rack",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shelf",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_administration",
                to="esl.company",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filial_employee",
                to="esl.companyfilial",
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="filial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filial",
                to="esl.companyfilial",
            ),
        ),
        migrations.AddField(
            model_name="eslerror",
            name="esl",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esl_error",
                to="esl.esl",
            ),
        ),
        migrations.AddField(
            model_name="esl",
            name="firmware",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firmware",
                to="esl.firmware",
            ),
        ),
        migrations.DeleteModel(
            name="Integration",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="OrganizationFilial",
        ),
    ]
