# Generated by Django 5.2.6 on 2026-02-23 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0011_company_companyfilial_eslerror_firmware_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="integration_login",
            new_name="container_id",
        ),
        migrations.RemoveField(
            model_name="company",
            name="integration_password",
        ),
        migrations.RemoveField(
            model_name="company",
            name="integration_url",
        ),
        migrations.AlterField(
            model_name="eslerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 2, 23, 18, 14, 19, 179877),
                null=True,
            ),
        ),
    ]
