# Generated by Django 5.2.6 on 2026-02-25 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0012_rename_integration_login_company_container_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.TextField(
                blank=True,
                choices=[("admin", "Admin"), ("employee", "Employee")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eslerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 2, 25, 15, 25, 24, 505679),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmware",
            name="date_add",
            field=models.DateField(
                blank=True, default=datetime.date(2026, 2, 25), null=True
            ),
        ),
    ]
