# Generated by Django 5.2.6 on 2026-03-11 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0013_userprofile_role_alter_eslerror_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eslerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 3, 11, 15, 58, 9, 267392),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmware",
            name="date_add",
            field=models.DateField(
                blank=True, default=datetime.date(2026, 3, 11), null=True
            ),
        ),
    ]
