# Generated by Django 5.2.6 on 2026-03-11 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0014_alter_eslerror_date_alter_firmware_date_add"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="integration_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="integration_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eslerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 3, 11, 15, 58, 49, 703767),
                null=True,
            ),
        ),
    ]
