# Generated by Django 5.2.6 on 2026-03-24 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0015_company_integration_type_company_integration_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eslerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 3, 25, 3, 33, 47, 833537),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmware",
            name="date_add",
            field=models.DateField(
                blank=True, default=datetime.date(2026, 3, 25), null=True
            ),
        ),
        migrations.AlterField(
            model_name="rack",
            name="column",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rack",
            name="row",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
