# Generated by Django 5.2.6 on 2026-03-25 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0016_alter_eslerror_date_alter_firmware_date_add_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eslerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 3, 26, 2, 20, 19, 789075),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmware",
            name="date_add",
            field=models.DateField(
                blank=True, default=datetime.date(2026, 3, 26), null=True
            ),
        ),
    ]
