# Generated by Django 5.2.6 on 2026-05-27 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0017_company_end_time_company_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eslerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 5, 27, 22, 16, 8, 948395),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmware",
            name="date_add",
            field=models.DateField(
                blank=True, default=datetime.date(2026, 5, 27), null=True
            ),
        ),
    ]
