# Generated by Django 5.2.6 on 2026-06-08 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0018_alter_eslerror_date_alter_firmware_date_add"),
    ]

    operations = [
        migrations.AddField(
            model_name="eslerror",
            name="status",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eslerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 6, 8, 23, 21, 55, 342123),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="firmware",
            name="date_add",
            field=models.DateField(
                blank=True, default=datetime.date(2026, 6, 8), null=True
            ),
        ),
    ]
