# Generated by Django 5.2.6 on 2026-06-08 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esl", "0019_eslerror_status_alter_eslerror_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eslerror",
            name="channel",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eslerror",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2026, 6, 8, 23, 36, 29, 232600),
                null=True,
            ),
        ),
    ]
