openapi: '3.0.3'
info:
  title: Service for ESL
  version: '1.0'
servers:
  - url: http://localhost/
tags:
  - name: auth
    description: Методы, связанные с аутентификацией
  - name: profile
    description: Методы, связанные с профилем

paths:
  /api/auth/login/:
    post:
      tags: 
        - auth
      summary: Получение пары токенов по имени пользователя и паролю. В будущем будет заменено на читательский билет и другие способы авторизации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '401':
          description: Unauthorized
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /api/auth/logout/:
    post:
      tags: 
        - auth
      summary: Инвалидация refresh токена
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
      responses:
        '401':
          description: Unauthorized
        '200':
          description: OK

  /api/profile/self-info/:
    get:
      tags:
        - profile
      summary: Получение информации о пользователе
      security:
        - bearer: []
      responses:
        '401':
          description: Unauthorized
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileInfo'


components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer токен, помещаемый в заголовок Authorization

  schemas:
    Tokens:
      type: object
      description: Пара токенов access и refresh
      properties:
        access:
          description: Токен, помещаемый в заголовок Authorization
          type: string
        refresh:
          description: Токен, использующийся для получения новой пары токенов
          type: string
    
    ProfileInfo:
      type: object
      description: Информация о пользователе
      properties:
        username:
          description: username пользователя
          type: string
        first_name:
          description: Имя 
          type: string
        last_name:
          description: Фамилия
          type: string
        groups:
          description: Группы пользователя
          type: array
          items:
            type: string
            enum:
              - Reader
              - Librarian

    