openapi: '3.0.3'
info:
  title: Service for ESL
  version: '1.0'
servers:
  - url: http://localhost/
tags:
  - name: auth
    description: Методы, связанные с аутентификацией
  - name: profile
    description: Методы, связанные с профилем
  - name: company
    description: Методы, связанные с компаниями
  - name: filial
    description: Методы, связанные с филиалами
  - name: rack
    description: Методы, связанные со стеллажами
  - name: product
    description: Методы, связанные с продуктами
  - name: esl
    description: Методы, связанные с электронными ценниками
  - name: integration
    description: Методы, связанные с интеграциями внешних систем
  - name: force
    description: Методы принудительного обновления информации

paths:
  /api/auth/login/:
    post:
      tags: 
        - auth
      summary: Получение пары токенов по имени пользователя и паролю.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '401':
          description: Unauthorized
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /api/auth/logout/:
    post:
      tags: 
        - auth
      summary: Инвалидация refresh токена
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
      responses:
        '401':
          description: Unauthorized
        '200':
          description: OK

  /api/profile/self-info/:
    get:
      tags:
        - profile
      summary: Получение информации о пользователе
      security:
        - bearer: []
      responses:
        '401':
          description: Unauthorized
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileInfo'
  
  /api/filial/:
    get:
      tags:
        - filial
      security:
        - bearer: []
      summary: Получение списка филиалов
      responses:
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilialsList'

  /api/filial/{id}/:
    get:
      tags:
        - filial
      security:
        - bearer: []
      summary: Получение информации о филиале по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            description: ID филиала
      responses:
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilialInfo'

  /api/product/show/:
    get:
      tags:
        - product
      summary: Получение полной информации о продукте
      parameters:
        - name: company
          in: query
          required: true
          schema:
            type: string
            description: ID компании
        - name: product
          in: query
          required: true
          schema:
            type: string
            description: ID товара
      responses:
        '404':
          description: Not Found
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductToShow"

  /api/product/:
    get:
      tags:
        - product
      security:
        - bearer: []
      summary: Получение списка товаров для текущей компании
      responses:
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    short_name:
                      type: string
                    barcode:
                      type: string

    post:
      tags:
        - product
      summary: Обновление информации о товарах
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/ProductUpdates"
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе      

  /api/esl/:
    post:
      tags:
        - esl
      summary: Добавление нового устройства
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ESLToAdd'
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе

    get:
      tags:
        - esl
      summary: Получение списка устройств
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе

  /api/esl/error/:
    post:
      tags:
        - esl
      security:
        - bearer: []
      summary: Создание ошибки
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ESLError'
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

    get:
      tags:
        - esl
      security:
        - bearer: []
      summary: Получение статистики по ошибкам устройств
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

  /api/esl/report/:
    get:
      tags:
        - esl
      security:
        - bearer: []
      summary: Получение статистики по отправке задач на обновление
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

  /api/esl/firmware/:
    get:
      tags:
        - esl
      security:
        - bearer: []
      summary: Получение информации о загруженных прошивках
      responses:
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    firmware:
                      type: string
                    upload_date:
                      type: string
                      format: date
      
    post:
      tags:
        - esl
      security:
        - bearer: []
      summary: Загрузка новой прошивки
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firmware:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

    put:
      tags:
        - esl
      security:
        - bearer: []
      summary: Обновление прошивки у устройств
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  filial:
                    type: number
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

  /api/rack/{id}/:
    get:
      tags:
        - rack
      security:
        - bearer: []
      summary: Получение информации о стеллаже по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            description: ID стеллажа
      responses:
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rack'
    put:
      tags:
        - rack
      security:
        - bearer: []
      summary: Изменение информации о стеллаже по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            description: ID стеллажа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rack'
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

    delete:
      tags:
        - rack
      security:
        - bearer: []
      summary: Удаление стеллажа по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            description: ID стеллажа
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

  /api/rack/:
    post:
      tags:
        - rack
      security:
        - bearer: []
      summary: Создание нового стеллажа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RackToCreate'
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

  /api/company/:
    get:
      tags:
        - company
      security:
        - bearer: []
      summary: Получение списка организаций в доступе у текущего пользователя
      responses:
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
    
  /api/company/{id}/:
    get:
      tags:
        - company
      security:
        - bearer: []
      summary: Получение информации об организации по ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            description: ID организации
      responses:
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
  
  /api/integration/:
    post:
      tags:
        - integration
      security:
        - bearer: []
      summary: Создание интеграции для компании
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IntegrationToCreate'
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

  /api/integration/{id}:
    get:
      tags:
        - integration
      security:
        - bearer: []
      summary: Получение информации об интеграции компании
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            description: ID организации
      responses:
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
    put:
      tags:
        - integration
      security:
        - bearer: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            description: ID интеграции
      summary: Обновление информации для интеграции
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        
    delete:
      tags:
        - integration
      security:
        - bearer: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            description: ID интеграции
      summary: Удаление интеграции
      responses:
        '200':
          description: OK
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden

  /api/integration/health/{id}:
    get:
      tags:
        - integration
      security:
        - bearer: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            description: ID интеграции
      summary: Получение сведений о состоянии интеграции
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ready: 
                    type: boolean
                  company:
                    type: boolean
                  products:
                    type: boolean
        '400':
          description: Ошибка в запросе
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
  
  /api/product/update/:
    get:
      tags:
        - force
      security:
        - bearer: []
      summary: ПРинудительное обновление информации о товарах на ценниках
      responses:
        '401':
          description: Unauthorized
        '403':
          description: Forbiden
        '200':
          description: OK

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer токен, помещаемый в заголовок Authorization

  schemas:
    Tokens:
      type: object
      description: Пара токенов access и refresh
      properties:
        access:
          description: Токен, помещаемый в заголовок Authorization
          type: string
        refresh:
          description: Токен, использующийся для получения новой пары токенов
          type: string
    
    ProfileInfo:
      type: object
      description: Информация о пользователе
      properties:
        username:
          description: username пользователя
          type: string
        first_name:
          description: Имя 
          type: string
        last_name:
          description: Фамилия
          type: string
        groups:
          description: Группы пользователя
          type: array
          items:
            type: string
            enum:
              - Reader
              - Librarian

    FilialToList:
      type: object
      description: Филиал
      properties:
        address: 
          type: string
        name: 
          type: string
          
    FilialsList:
      type: array
      items: 
        $ref: '#/components/schemas/FilialToList'

    Product:
      type: object
      properties:
        barcode:
          type: string
        shelf:
          type: number
        number:
          type: number

    Rack:
      type: object
      properties:
        number:
          type: number
        ip:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'

    RackToCreate:
      type: object
      properties:
        company:
          type: number
        number:
          type: number
        ip:
          type: string
    
    FilialInfo:
      type: object
      properties:
        name: 
          type: string
        address:
          type: string
        rack:
          type: array
          items:
            $ref: '#/components/schemas/Rack'

    ESLError:
      type: object
      properties:
        error_type:
          type: string
          description: Тип ошибки
          enum:
            - display
            - nfc
        error_time:
          type: string
          format: datetime
        error_number:
          type: number
    
    ESLToAdd:
      type: object
      properties:
        rack:
          type: number
        token:
          type: string
    
    ProductToShow:
      type: object
      properties:
        short_name:
          type: string
        old_price:
          type: number
        current_price:
          type: number
        have_promotion:
          type: boolean
        description: 
          type: string
        photo:
          type: string

    ProductUpdates:
      type: object
      properties:
        product_id: 
          type: string
        short_name:
          type: string
        old_price:
          type: number
        current_price:
          type: number
        have_promotion:
          type: boolean
    
    Company:
      type: object
      properties:
        name: 
          type: string

    IntegrationToCreate:
      type: object
      properties:
        company:
          type: number
        login:
          type: string
        password:
          type: string
        url:
          type: string
        intervals:
          type: number